import Head from "next/head";
import Link from "next/link";
import GifBackground from '../components/GifBackground.js';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Trie</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GifBackground />
            <div className={"flex justify-center items-center h-screen"}>
                <div className="flex-initial">
                    <h1 className="text-3xl text-center text-5xl text-white font-bold uppercase">
                        Trie Application
                    </h1>
                    <div className="flex justify-center my-5">
                        <button className="w-fit bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                            <Link href={"./citizen_info"}>
                                Lookup Top 100 Footballer 
                            </Link>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
}
