import Head from "next/head";
import Link from 'next/link';

export default function Home() {
    return (
        <div
            className={
                "w-screen h-screen bg-slate-300 flex justify-center items-center"
            }
        >
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-screen flex-initial">
                <h1 className="text-3xl text-center text-5xl font-bold uppercase">
                    Trie Application
                </h1>
                <div className="flex justify-center my-5">
                    <button class="w-fit bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                        <Link href={'./citizen_info'}>Search Citizen Information</Link>
                    </button>
                </div>
            </div>
        </div>
    );
}
